<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AgentFramework.Llm</RootNamespace>
    <AssemblyName>AgentFramework.Llm</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AgentFramework.Contracts/AgentFramework.Contracts.csproj" />
  </ItemGroup>

</Project>
