<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>AgentFramework.VerifyTools</RootNamespace>
    <AssemblyName>AgentFramework.VerifyTools</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/AgentFramework.Tools/AgentFramework.Tools.csproj" />
    <ProjectReference Include="../../src/AgentFramework.Agent/AgentFramework.Agent.csproj" />
    <ProjectReference Include="../../src/AgentFramework.Data/AgentFramework.Data.csproj" />
    <ProjectReference Include="../../src/AgentFramework.Kernel/AgentFramework.Kernel.csproj" />
  </ItemGroup>

</Project>
