<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AgentFramework.Sandbox</RootNamespace>
    <AssemblyName>AgentFramework.Sandbox</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AgentFramework.Contracts/AgentFramework.Contracts.csproj" />
  </ItemGroup>

</Project>
